name: Deployment Exercise 2
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: './04 Practice Project (Start)/src/test'
      - name: Lint
        run: npm run lint
        working-directory: './04 Practice Project (Start)/src/test'
      - name: Test code
        run: npm run test
        working-directory: './04 Practice Project (Start)/src/test'
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci 
        working-directory: './04 Practice Project (Start)/src/test'
      - name: Build code
        run: npm run build
        working-directory: './04 Practice Project (Start)/src/test'
      - name: Deploy code
        run: echo "Deploying..."